import { PainPoint } from '../types';

export const PAIN_POINTS: PainPoint[] = [
  // Financial
  { name: "Living Paycheck to Paycheck", emoji: "💸", description: "Feeling stressed as money runs out before the next payday.", category: "Financial" },
  { name: "Student Loan Debt", emoji: "🎓", description: "The overwhelming burden of paying off education loans.", category: "Financial" },
  { name: "Lack of Retirement Savings", emoji: "👵", description: "Worrying about not having enough money for retirement.", category: "Financial" },
  { name: "Poor Credit Score", emoji: "📉", description: "Being denied loans or favorable rates due to a low credit score.", category: "Financial" },
  { name: "Impulse Spending", emoji: "🛍️", description: "Buying things without planning, leading to budget problems.", category: "Financial" },
  { name: "Managing Bills", emoji: "🧾", description: "The hassle of tracking and paying multiple bills on time.", category: "Financial" },
  { name: "Financial Illiteracy", emoji: "🤔", description: "Not understanding complex financial topics like investing or taxes.", category: "Financial" },
  { name: "Unexpected Expenses", emoji: "💥", description: "Sudden costs like car repairs or medical bills disrupting finances.", category: "Financial" },
  { name: "Saving for a Down Payment", emoji: "🏡", description: "The struggle to save enough money to buy a home.", category: "Financial" },
  { name: "High Cost of Living", emoji: "🏙️", description: "Feeling that basic necessities are becoming unaffordable.", category: "Financial" },
  { name: "Investment Anxiety", emoji: "📈", description: "Fear of making the wrong investment decisions and losing money.", category: "Financial" },
  { name: "Negotiating Salary", emoji: "💼", description: "Feeling uncomfortable or unskilled when asking for a raise.", category: "Financial" },
  { name: "Filing Taxes", emoji: "📝", description: "The complexity and stress of tax season.", category: "Financial" },
  { name: "Credit Card Debt", emoji: "💳", description: "The cycle of high-interest debt from credit card balances.", category: "Financial" },
  { name: "Lack of Emergency Fund", emoji: "🚨", description: "Not having a financial cushion for unexpected job loss or emergencies.", category: "Financial" },

  // Health & Wellness
  { name: "Chronic Back Pain", emoji: "🤕", description: "Persistent discomfort in the back affecting daily life.", category: "Health & Wellness" },
  { name: "Insomnia or Poor Sleep", emoji: "😴", description: "Difficulty falling asleep or staying asleep, leading to fatigue.", category: "Health & Wellness" },
  { name: "Anxiety and Stress", emoji: "😟", description: "Constant feelings of worry, nervousness, or unease.", category: "Health & Wellness" },
  { name: "Weight Management", emoji: "⚖️", description: "Struggling to lose, gain, or maintain a healthy weight.", category: "Health & Wellness" },
  { name: "Lack of Motivation to Exercise", emoji: "🏃‍♀️", description: "Knowing you should work out but finding it hard to start.", category: "Health & Wellness" },
  { name: "Unhealthy Eating Habits", emoji: "🍔", description: "Relying on junk food or overeating despite knowing the consequences.", category: "Health & Wellness" },
  { name: "Frequent Headaches", emoji: "🤯", description: "Dealing with regular headaches or migraines.", category: "Health & Wellness" },
  { name: "Digital Eye Strain", emoji: "👀", description: "Eye discomfort from spending too much time on screens.", category: "Health & Wellness" },
  { name: "Allergies", emoji: "🤧", description: "Seasonal or chronic allergies causing sneezing, itching, and discomfort.", category: "Health & Wellness" },
  { name: "Low Energy Levels", emoji: "⚡", description: "Feeling tired and sluggish throughout the day.", category: "Health & Wellness" },
  { name: "Depression", emoji: "😔", description: "Persistent feelings of sadness and loss of interest.", category: "Health & Wellness" },
  { name: "Finding a Good Doctor", emoji: "👨‍⚕️", description: "The difficulty of finding a trusted and available healthcare provider.", category: "Health & Wellness" },
  { name: "Managing a Chronic Illness", emoji: "💊", description: "The daily challenge of living with a long-term health condition.", category: "Health & Wellness" },
  { name: "Meal Planning for Health", emoji: "🥗", description: "The effort it takes to plan and prepare healthy meals.", category: "Health & Wellness" },
  { name: "Staying Hydrated", emoji: "💧", description: "Forgetting to drink enough water during the day.", category: "Health & Wellness" },

  // Career & Professional
  { name: "Job Dissatisfaction", emoji: "😒", description: "Feeling unfulfilled, bored, or unhappy with your current job.", category: "Career & Professional" },
  { name: "Burnout", emoji: "🔥", description: "Feeling emotionally, physically, and mentally exhausted from work.", category: "Career & Professional" },
  { name: "Imposter Syndrome", emoji: "🎭", description: "Feeling like a fraud at work, despite being successful.", category: "Career & Professional" },
  { name: "Difficult Coworkers", emoji: "🗣️", description: "Dealing with challenging or toxic colleagues.", category: "Career & Professional" },
  { name: "Lack of Career Growth", emoji: "🌱", description: "Feeling stuck in a role with no opportunities for advancement.", category: "Career & Professional" },
  { name: "Poor Work-Life Balance", emoji: "⚖️", description: "Work taking over personal time and causing stress.", category: "Career & Professional" },
  { name: "Job Searching", emoji: "🔍", description: "The stressful and often lengthy process of finding a new job.", category: "Career & Professional" },
  { name: "Public Speaking Anxiety", emoji: "🎤", description: "Fear of speaking in front of groups or giving presentations.", category: "Career & Professional" },
  { name: "Procrastination", emoji: "⏳", description: "Delaying important tasks, leading to stress and missed deadlines.", category: "Career & Professional" },
  { name: "Distractions at Work", emoji: "📱", description: "Difficulty concentrating at work due to interruptions and digital distractions.", category: "Career & Professional" },
  { name: "Networking Discomfort", emoji: "🤝", description: "Feeling awkward or insincere when trying to make professional connections.", category: "Career & Professional" },
  { name: "Micromanagement", emoji: "👀", description: "Frustration from a boss who is overly controlling and observant.", category: "Career & Professional" },
  { name: "Skill Gaps", emoji: "🤷", description: "Worrying that your skills are becoming outdated.", category: "Career & Professional" },
  { name: "Commuting Stress", emoji: "🚗", description: "The daily grind of traffic, delays, and long travel times to work.", category: "Career & Professional" },
  { name: "Endless Meetings", emoji: "🗣", description: "Feeling that too much time is wasted in unproductive meetings.", category: "Career & Professional" },

  // Social & Relationships
  { name: "Loneliness", emoji: "👤", description: "Feeling isolated and lacking meaningful social connections.", category: "Social & Relationships" },
  { name: "Making New Friends", emoji: "👯", description: "The difficulty of meeting new people and forming friendships as an adult.", category: "Social & Relationships" },
  { name: "Dating App Fatigue", emoji: "💔", description: "Feeling exhausted and disillusioned by online dating.", category: "Social & Relationships" },
  { name: "Social Anxiety", emoji: "😰", description: "Intense fear or discomfort in social situations.", category: "Social & Relationships" },
  { name: "Family Conflict", emoji: "👨‍👩‍👧‍👦", description: "Dealing with disagreements and tension within the family.", category: "Social & Relationships" },
  { name: "Maintaining Long-Distance Friendships", emoji: "✈️", description: "The challenge of staying close with friends who live far away.", category: "Social & Relationships" },
  { name: "Feeling Misunderstood", emoji: "💬", description: "The frustration of others not getting your point of view.", category: "Social & Relationships" },
  { name: "Peer Pressure", emoji: "👥", description: "Feeling forced to do something you're not comfortable with.", category: "Social & Relationships" },
  { name: "Breakups and Heartbreak", emoji: "💔", description: "The emotional pain of ending a romantic relationship.", category: "Social & Relationships" },
  { name: "Fear of Missing Out (FOMO)", emoji: "😮", description: "Anxiety that you might miss out on exciting or interesting events.", category: "Social & Relationships" },
  { name: "Remembering Birthdays/Anniversaries", emoji: "🎂", description: "Forgetting important dates and feeling guilty.", category: "Social & Relationships" },
  { name: "Difficult Conversations", emoji: "🗣️", description: "Avoiding or struggling with necessary but uncomfortable talks.", category: "Social & Relationships" },
  { name: "Finding a Compatible Partner", emoji: "❤️", description: "The search for someone who shares your values and interests.", category: "Social & Relationships" },
  { name: "Comparison to Others on Social Media", emoji: "📱", description: "Feeling inadequate after seeing others' curated lives online.", category: "Social & Relationships" },
  { name: "Hosting Events", emoji: "🎉", description: "The stress of planning and hosting parties or get-togethers.", category: "Social & Relationships" },

  // Household & Domestic
  { name: "Clutter and Disorganization", emoji: "🏠", description: "Feeling overwhelmed by the amount of stuff in your home.", category: "Household & Domestic" },
  { name: "Cleaning and Chores", emoji: "🧹", description: "The never-ending cycle of cleaning the house.", category: "Household & Domestic" },
  { name: "Cooking Dinner Every Night", emoji: "🍳", description: "The daily chore of deciding what to cook and preparing it.", category: "Household & Domestic" },
  { name: "Grocery Shopping", emoji: "🛒", description: "The time and effort spent on buying groceries each week.", category: "Household & Domestic" },
  { name: "Home Repairs", emoji: "🛠️", description: "The hassle and cost of fixing things that break around the house.", category: "Household & Domestic" },
  { name: "Laundry", emoji: "🧺", description: "The constant task of washing, drying, and folding clothes.", category: "Household & Domestic" },
  { name: "Yard Work", emoji: "🌿", description: "Maintaining a lawn, garden, or outdoor space.", category: "Household & Domestic" },
  { name: "Finding Reliable Service Providers", emoji: "👷", description: "The difficulty of finding trustworthy plumbers, electricians, etc.", category: "Household & Domestic" },
  { name: "Pest Problems", emoji: "🐜", description: "Dealing with unwanted insects or rodents in the home.", category: "Household & Domestic" },
  { name: "Wasted Food", emoji: "🍎", description: "Throwing away food that has gone bad before it could be eaten.", category: "Household & Domestic" },
  { name: "High Utility Bills", emoji: "💡", description: "Worrying about the cost of electricity, water, and gas.", category: "Household & Domestic" },
  { name: "Lack of Storage Space", emoji: "📦", description: "Not having enough room to store all of your belongings.", category: "Household & Domestic" },
  { name: "Moving Houses", emoji: "🚚", description: "The stressful and physically demanding process of relocating.", category: "Household & Domestic" },
  { name: "Pet Care", emoji: "🐾", description: "Managing the responsibilities of feeding, walking, and caring for pets.", category: "Household & Domestic" },
  { name: "Roommate Issues", emoji: "😠", description: "Conflicts and difficulties living with roommates.", category: "Household & Domestic" },

  // Personal Growth & Hobbies
  { name: "Finding a New Hobby", emoji: "🎨", description: "Wanting to learn something new but not knowing where to start.", category: "Personal Growth & Hobbies" },
  { name: "Learning a New Language", emoji: "🗣️", description: "The difficulty and time commitment of becoming fluent in a new language.", category: "Personal Growth & Hobbies" },
  { name: "Breaking Bad Habits", emoji: "🚬", description: "Struggling to stop habits like nail-biting, smoking, or overspending.", category: "Personal Growth & Hobbies" },
  { name: "Lack of Creativity", emoji: "💡", description: "Feeling uninspired or stuck in a creative rut.", category: "Personal Growth & Hobbies" },
  { name: "Reading More Books", emoji: "📚", description: "Wanting to read more but not finding the time or focus.", category: "Personal Growth & Hobbies" },
  { name: "Sticking to a Routine", emoji: "📅", description: "The challenge of maintaining a consistent daily schedule.", category: "Personal Growth & Hobbies" },
  { name: "Fear of Failure", emoji: "😬", description: "Being so afraid of failing that you don't even try new things.", category: "Personal Growth & Hobbies" },
  { name: "Finding a Mentor", emoji: "👨‍🏫", description: "The difficulty of finding someone experienced to guide you.", category: "Personal Growth & Hobbies" },
  { name: "Building Confidence", emoji: "💪", description: "Struggling with self-doubt and low self-esteem.", category: "Personal Growth & Hobbies" },
  { name: "Time for Hobbies", emoji: "🎸", description: "Having hobbies you love but no time to pursue them.", category: "Personal Growth & Hobbies" },
  { name: "Practicing a Musical Instrument", emoji: "🎹", description: "The discipline required to practice and improve on an instrument.", category: "Personal Growth & Hobbies" },
  { name: "Overcoming Writer's Block", emoji: "✍️", description: "Staring at a blank page, unable to start writing.", category: "Personal Growth & Hobbies" },
  { name: "Developing Self-Discipline", emoji: "🧘", description: "The struggle to stay focused on long-term goals.", category: "Personal Growth & Hobbies" },
  { name: "Finding Purpose", emoji: "🧭", description: "Feeling lost or unsure about your direction in life.", category: "Personal Growth & Hobbies" },
  { name: "Managing Personal Projects", emoji: "🛠", description: "Juggling personal goals and projects outside of work.", category: "Personal Growth & Hobbies" },
  
  // Technology & Digital Life
  { name: "Information Overload", emoji: "쏟", description: "Feeling overwhelmed by the constant stream of news and information.", category: "Technology & Digital Life" },
  { name: "Password Management", emoji: "🔑", description: "The frustration of forgetting passwords or keeping them secure.", category: "Technology & Digital Life" },
  { name: "Social Media Addiction", emoji: "📱", description: "Spending too much time scrolling and feeling unable to stop.", category: "Technology & Digital Life" },
  { name: "Email Overload", emoji: "📧", description: "A constantly full inbox causing stress and disorganization.", category: "Technology & Digital Life" },
  { name: "Data Privacy Concerns", emoji: "🔒", description: "Worrying about how personal data is being used by companies.", category: "Technology & Digital Life" },
  { name: "Slow Internet", emoji: "🐌", description: "Frustration with unreliable or slow internet connections.", category: "Technology & Digital Life" },
  { name: "Tech Support Issues", emoji: "💻", description: "The difficulty of getting help when devices or software don't work.", category: "Technology & Digital Life" },
  { name: "Managing Digital Photos", emoji: "🖼️", description: "Having thousands of digital photos with no organization.", category: "Technology & Digital Life" },
  { name: "Too Many Subscriptions", emoji: "갱", description: "Losing track of and overpaying for various online subscriptions.", category: "Technology & Digital Life" },
  { name: "Finding Unbiased Reviews", emoji: "⭐", description: "Struggling to find trustworthy reviews for products and services.", category: "Technology & Digital Life" },
  { name: "Online Harassment", emoji: "🗯️", description: "Dealing with negativity, trolls, and cyberbullying.", category: "Technology & Digital Life" },
  { name: "Keeping up with Technology", emoji: "🤖", description: "Feeling that technology is changing too fast to keep up.", category: "Technology & Digital Life" },
  { name: "Software Complexity", emoji: "🧩", description: "Frustration with software that is too complicated to use.", category: "Technology & Digital Life" },
  { name: "Digital Detox", emoji: "🔌", description: "Wanting to disconnect from screens but finding it difficult.", category: "Technology & Digital Life" },
  { name: "Battery Life Anxiety", emoji: "🔋", description: "The constant worry that your phone or laptop will run out of power.", category: "Technology & Digital Life" },

  // Parenting & Family
  { name: "Picky Eaters", emoji: "🥦", description: "The struggle to get children to eat healthy and varied foods.", category: "Parenting & Family" },
  { name: "Tantrums", emoji: "😡", description: "Managing young children's emotional outbursts.", category: "Parenting & Family" },
  { name: "Finding Quality Childcare", emoji: "👶", description: "The stressful search for affordable and reliable childcare.", category: "Parenting & Family" },
  { name: "Juggling Kids' Schedules", emoji: "🗓️", description: "Coordinating school, sports, and other activities for multiple children.", category: "Parenting & Family" },
  { name: "Screen Time Battles", emoji: "🎮", description: "Arguing with kids about the amount of time they spend on devices.", category: "Parenting & Family" },
  { name: "Helping with Homework", emoji: "📚", description: "The challenge of assisting children with schoolwork you don't understand.", category: "Parenting & Family" },
  { name: "Lack of 'Me Time'", emoji: "🧘‍♀️", description: "Parents feeling they have no personal time for themselves.", category: "Parenting & Family" },
  { name: "Saving for College", emoji: "🎓", description: "The financial pressure of saving for a child's higher education.", category: "Parenting & Family" },
  { name: "Caring for Aging Parents", emoji: "👴", description: "The emotional and logistical challenges of elder care.", category: "Parenting & Family" },
  { name: "Co-Parenting Challenges", emoji: "👨‍👧‍👦", description: "Navigating parenting responsibilities after a separation.", category: "Parenting & Family" },
  { name: "Sibling Rivalry", emoji: "🤼", description: "Dealing with fighting and competition between your children.", category: "Parenting & Family" },
  { name: "Keeping the House Tidy with Kids", emoji: "🧸", description: "The constant battle against toys and mess.", category: "Parenting & Family" },
  { name: "Parental Guilt", emoji: "😔", description: "Worrying if you are making the right decisions for your children.", category: "Parenting & Family" },
  { name: "Finding Kid-Friendly Activities", emoji: "🎈", description: "The constant search for new and engaging things to do as a family.", category: "Parenting & Family" },
  { name: "Sleep Deprivation (New Parents)", emoji: "😴", description: "The exhaustion that comes with caring for a newborn.", category: "Parenting & Family" },

  // Travel & Leisure
  { name: "Planning a Vacation", emoji: "🗺️", description: "The overwhelming process of researching and booking a trip.", category: "Travel & Leisure" },
  { name: "Packing Stress", emoji: "🧳", description: "The anxiety of what to pack and fitting it all in a suitcase.", category: "Travel & Leisure" },
  { name: "Airport Hassles", emoji: "✈️", description: "Dealing with security lines, delays, and crowded airports.", category: "Travel & Leisure" },
  { name: "Finding Authentic Local Experiences", emoji: "✨", description: "Struggling to find genuine cultural experiences and avoid tourist traps.", category: "Travel & Leisure" },
  { name: "Jet Lag", emoji: "😴", description: "The fatigue and disorientation after traveling across time zones.", category: "Travel & Leisure" },
  { name: "Budgeting for Travel", emoji: "💰", description: "The challenge of planning a trip without overspending.", category: "Travel & Leisure" },
  { name: "Language Barriers", emoji: "🗣️", description: "Difficulty communicating when traveling in a foreign country.", category: "Travel & Leisure" },
  { name: "Feeling Unsafe While Traveling", emoji: "😨", description: "Concerns about safety and security in unfamiliar places.", category: "Travel & Leisure" },
  { name: "Boredom", emoji: "🥱", description: "Having free time but not knowing what to do with it.", category: "Travel & Leisure" },
  { name: "Finding Travel Companions", emoji: "👫", description: "Wanting to travel but not having anyone to go with.", category: "Travel & Leisure" },
  { name: "Post-Vacation Blues", emoji: "😔", description: "The sadness of returning to routine after a wonderful trip.", category: "Travel & Leisure" },
  { name: "Overcrowded Tourist Spots", emoji: "👨‍👩‍👧‍👦", description: "The disappointment of visiting popular destinations only to find them packed with people, diminishing the experience.", category: "Travel & Leisure" },
  { name: "Finding Pet-Friendly Accommodations", emoji: "🐾", description: "The difficulty of finding places to stay when traveling with pets.", category: "Travel & Leisure" },
  { name: "Motion Sickness", emoji: "🤢", description: "Feeling sick during travel by car, boat, or plane.", category: "Travel & Leisure" },

  // Nigerian Pain Points
  { name: "Unstable Power Supply (NEPA/PHCN)", emoji: "💡", description: "The constant struggle with erratic electricity, forcing reliance on noisy and expensive generators.", category: "Nigerian Pain Points" },
  { name: "Bad Road Networks", emoji: "🚗", description: "Navigating potholes and poorly maintained roads, leading to vehicle damage and long travel times.", category: "Nigerian Pain Points" },
  { name: "High Cost of Internet Data", emoji: "📶", description: "Paying a premium for mobile data that is often slow and unreliable.", category: "Nigerian Pain Points" },
  { name: "Fuel Scarcity and Queues", emoji: "⛽", description: "The periodic stress of petrol shortages, leading to long waits and inflated prices.", category: "Nigerian Pain Points" },
  { name: "Navigating Lagos Traffic", emoji: "🚙", description: "Losing countless hours to gridlock, especially in major commercial hubs.", category: "Nigerian Pain Points" },
  { name: "Currency Fluctuation (Naira Instability)", emoji: "💲", description: "The financial anxiety caused by the unpredictable value of the Naira against the dollar.", category: "Nigerian Pain Points" },
  { name: "Finding Reliable Artisans", emoji: "🛠️", description: "The frustrating search for skilled and trustworthy plumbers, electricians, and mechanics.", category: "Nigerian Pain Points" },
  { name: "Poor Customer Service", emoji: "😠", description: "Dealing with indifferent or unhelpful staff in banks, telecom companies, and other businesses.", category: "Nigerian Pain Points" },
  { name: "Complex Importation/Customs", emoji: "🚢", description: "The bureaucratic hurdles and unpredictable costs of clearing goods at the port.", category: "Nigerian Pain Points" },
  { name: "Insecurity and Kidnapping Threats", emoji: "😨", description: "The constant background anxiety about personal safety and the risk of crime.", category: "Nigerian Pain Points" },
  { name: "Unemployment and Underemployment", emoji: "👨‍🎓", description: "The struggle for graduates and skilled individuals to find meaningful, well-paying jobs.", category: "Nigerian Pain Points" },
  { name: "Exorbitant Bank Charges", emoji: "🏦", description: "Frustration with numerous, often unexplained, fees and deductions from bank accounts.", category: "Nigerian Pain Points" },
  { name: "Difficulty Accessing Loans", emoji: "💰", description: "The challenge for individuals and small businesses to secure credit from traditional banks.", category: "Nigerian Pain Points" },
  { name: "Navigating Bureaucracy", emoji: "📜", description: "The slow and frustrating process of obtaining official documents like passports and driver's licenses.", category: "Nigerian Pain Points" },
  { name: "Substandard Education System", emoji: "🏫", description: "Worrying that the public education system is not equipping children with competitive skills.", category: "Nigerian Pain Points" },
  { name: "Access to Quality Healthcare", emoji: "🏥", description: "The high cost and variable quality of medical services, making proper healthcare a luxury.", category: "Nigerian Pain Points" },
  { name: "Finding Affordable Housing", emoji: "🏠", description: "The struggle to find decent and reasonably priced rental accommodation, especially in cities.", category: "Nigerian Pain Points" },
  { name: "Police Harassment and Extortion", emoji: "👮", description: "The fear and frustration of dealing with illegal checkpoints and demands for bribes.", category: "Nigerian Pain Points" },
  { name: "Online Payment Failures", emoji: "💳", description: "The unreliability of digital payment gateways, causing transactions to fail frequently.", category: "Nigerian Pain Points" },
  { name: "Fake Product Proliferation", emoji: "🚫", description: "The difficulty in distinguishing genuine products from counterfeit ones in the market.", category: "Nigerian Pain Points" },
  { name: "Waste Management Issues", emoji: "🗑️", description: "Living with inadequate waste disposal systems, leading to environmental pollution.", category: "Nigerian Pain Points" },
  { name: "Noise Pollution", emoji: "🔊", description: "The constant barrage of noise from generators, religious centers, and commercial activities.", category: "Nigerian Pain Points" },
  { name: "Water Scarcity", emoji: "💧", description: "The lack of consistent access to clean, potable water for daily needs.", category: "Nigerian Pain Points" },
  { name: "Multiple Taxation for Businesses", emoji: "🧾", description: "The burden on small businesses from numerous official and unofficial levies and taxes.", category: "Nigerian Pain Points" },
  { name: "Lack of Social Safety Nets", emoji: "🤷", description: "Feeling vulnerable without government support during job loss, illness, or old age.", category: "Nigerian Pain Points" },

  // Small Business Owner Pain Points
  { name: "Managing Cash Flow", emoji: "💵", description: "The constant challenge of balancing money coming in and going out to keep the business afloat.", category: "Small Business Owner" },
  { name: "Finding New Customers", emoji: "🎯", description: "The struggle to consistently attract and acquire new clients or customers.", category: "Small Business Owner" },
  { name: "Hiring and Retaining Talent", emoji: "👥", description: "Competing with larger companies to find and keep skilled employees.", category: "Small Business Owner" },
  { name: "Wearing Too Many Hats", emoji: "🤠", description: "Feeling overwhelmed by having to be the CEO, marketer, accountant, and HR manager all at once.", category: "Small Business Owner" },
  { name: "Securing Funding or Loans", emoji: "🏦", description: "The difficult process of getting capital to start or grow the business.", category: "Small Business Owner" },
  { name: "Dealing with Late Payments", emoji: "🧾", description: "Chasing clients for invoices, which disrupts cash flow and strains relationships.", category: "Small Business Owner" },
  { name: "Keeping up with Regulations", emoji: "📜", description: "The complexity of navigating local, state, and federal business laws and taxes.", category: "Small Business Owner" },
  { name: "Marketing on a Small Budget", emoji: "📢", description: "Trying to get the word out and compete for attention without a large marketing spend.", category: "Small Business Owner" },
  { name: "Work-Life Balance", emoji: "⚖️", description: "The inability to 'switch off' from the business, leading to burnout.", category: "Small Business Owner" },
  { name: "Adopting New Technology", emoji: "💻", description: "Feeling overwhelmed by the cost and complexity of choosing and implementing the right tech tools.", category: "Small Business Owner" },

  // Investor Pain Points
  { name: "Finding Quality Deal Flow", emoji: "🔍", description: "The challenge of sourcing and identifying promising investment opportunities.", category: "Investor" },
  { name: "Market Volatility", emoji: "📈", description: "The anxiety of watching portfolio value fluctuate wildly due to market instability.", category: "Investor" },
  { name: "Conducting Due Diligence", emoji: "🧐", description: "The time-consuming and complex process of researching an investment to verify its claims.", category: "Investor" },
  { name: "Information Overload", emoji: "📰", description: "Sifting through a deluge of financial news and data to make informed decisions.", category: "Investor" },
  { name: "Emotional Investing (FOMO/FUD)", emoji: "😰", description: "Making irrational decisions based on fear of missing out or fear, uncertainty, and doubt.", category: "Investor" },
  { name: "Portfolio Diversification", emoji: "📊", description: "The difficulty of properly spreading investments across different assets to manage risk.", category: "Investor" },
  { name: "High Management Fees", emoji: "💸", description: "Concern that fees from funds and advisors are eating into investment returns.", category: "Investor" },
  { name: "Planning an Exit Strategy", emoji: "🚪", description: "The uncertainty of when and how to sell an investment for maximum profit.", category: "Investor" },

  // Software Engineer Pain Points
  { name: "Dealing with Legacy Code", emoji: "📜", description: "The frustration of working with old, poorly documented, and fragile codebases.", category: "Software Engineer" },
  { name: "Unclear or Changing Requirements", emoji: "❓", description: "Struggling to build a product when the goals and specifications are constantly shifting (scope creep).", category: "Software Engineer" },
  { name: "Unproductive Meetings", emoji: "🗓️", description: "Losing valuable coding time to meetings that lack a clear purpose or outcome.", category: "Software Engineer" },
  { name: "Debugging Complex Issues", emoji: "🐛", description: "The time-consuming and mentally draining process of finding the root cause of a bug.", category: "Software Engineer" },
  { name: "Pressure to Meet Tight Deadlines", emoji: "⏳", description: "The stress of having to deliver complex features under unrealistic time constraints.", category: "Software Engineer" },
  { name: "Keeping Up with New Technologies", emoji: "📚", description: "The constant pressure to learn new frameworks, languages, and tools to stay relevant.", category: "Software Engineer" },
  { name: "On-Call Rotations", emoji: " pager", description: "The anxiety and disrupted sleep from being responsible for system outages outside of work hours.", category: "Software Engineer" },
  { name: "Slow Code Reviews", emoji: "👀", description: "Having work blocked and momentum lost while waiting for feedback from teammates.", category: "Software Engineer" },

  // Graphic Designer Pain Points
  { name: "Vague Client Feedback", emoji: "🤔", description: "Receiving unhelpful feedback like 'make it pop' or 'I'll know it when I see it.'", category: "Graphic Designer" },
  { name: "Scope Creep", emoji: "➕", description: "Clients endlessly asking for 'just one more change' that goes beyond the original agreement.", category: "Graphic Designer" },
  { name: "Getting Paid on Time", emoji: "💰", description: "The stressful process of chasing clients for late payments after work has been completed.", category: "Graphic Designer" },
  { name: "Justifying Design Value", emoji: "💡", description: "Having to explain the importance and ROI of good design to clients who see it as a commodity.", category: "Graphic Designer" },
  { name: "Creative Block", emoji: "🧱", description: "Staring at a blank canvas and feeling a complete lack of inspiration or ideas.", category: "Graphic Designer" },
  { name: "Design by Committee", emoji: "👥", description: "Having too many stakeholders give conflicting feedback, resulting in a watered-down design.", category: "Graphic Designer" },
  { name: "Managing Fonts and Assets", emoji: "📂", description: "The organizational headache of keeping track of licenses, fonts, stock photos, and project files.", category: "Graphic Designer" },

  // Cybersecurity Expert Pain Points
  { name: "Alert Fatigue", emoji: "🚨", description: "Being overwhelmed by a constant stream of security alerts, making it hard to identify real threats.", category: "Cybersecurity Expert" },
  { name: "Keeping Up with New Threats", emoji: "📖", description: "The relentless pace of new vulnerabilities, attack vectors, and malware.", category: "Cybersecurity Expert" },
  { name: "User Awareness and Training", emoji: "🎣", description: "The ongoing struggle to prevent employees from falling for phishing scams and other social engineering.", category: "Cybersecurity Expert" },
  { name: "Communicating Risk to Leadership", emoji: "👨‍💼", description: "The challenge of translating complex technical risks into business impact that executives can understand.", category: "Cybersecurity Expert" },
  { name: "Budget and Resource Constraints", emoji: "💸", description: "Fighting for the necessary budget to implement essential security tools and hire talent.", category: "Cybersecurity Expert" },
  { name: "Burnout from High Stakes", emoji: "🔥", description: "The immense pressure and stress of being responsible for protecting the organization from costly breaches.", category: "Cybersecurity Expert" },
  { name: "Vendor and Tool Sprawl", emoji: "🧩", description: "Managing a complex and often disconnected set of security tools from various vendors.", category: "Cybersecurity Expert" },

  // Phobias & Fears
  { name: "Fear of heights", emoji: "🎢", description: "Feeling intense fear when high up.", category: "Phobias & Fears" },
  { name: "Fear of spiders", emoji: "🕷️", description: "An irrational fear of spiders.", category: "Phobias & Fears" },
  { name: "Fear of public restrooms", emoji: "🚽", description: "Anxiety about using public toilet facilities.", category: "Phobias & Fears" },
  { name: "Fear of flying", emoji: "✈️", description: "Intense anxiety about traveling in an airplane.", category: "Phobias & Fears" },
  { name: "Fear of the dark", emoji: "🌃", description: "A common fear of being in dark places.", category: "Phobias & Fears" },
  
  // Daily Annoyances
  { name: "Losing keys or wallet", emoji: "🔑", description: "The panic and inconvenience of misplacing essential items.", category: "Daily Annoyances" },
  { name: "Spam calls and texts", emoji: "📵", description: "The constant interruption from unwanted calls and messages.", category: "Daily Annoyances" },
  { name: "Traffic jams", emoji: "🚗", description: "The frustration of being stuck in slow-moving traffic.", category: "Daily Annoyances" },
  { name: "Waiting in line", emoji: "🚶‍♂️", description: "The boredom and time wasted queuing for services.", category: "Daily Annoyances" },
  { name: "Noisy neighbors", emoji: "🔊", description: "Disturbances from neighbors causing stress at home.", category: "Daily Annoyances" },
  { name: "Forgetting names", emoji: "🤦", description: "The awkwardness of not being able to recall someone's name.", category: "Social & Relationships" },
  { name: "Running late", emoji: "⏰", description: "The stress and anxiety of not being on time for appointments.", category: "Productivity & Time Management" },
  { name: "Finding parking", emoji: "🅿️", description: "The frustrating search for a parking spot.", category: "Daily Annoyances" },
  { name: "Assembling furniture", emoji: "🔩", description: "The confusing and often frustrating task of putting together flat-pack furniture.", category: "Household & Domestic" },
  { name: "Untangling wires", emoji: "🔌", description: "The mess and hassle of tangled cables and chargers.", category: "Technology & Digital Life" },
  { name: "Decision fatigue", emoji: "🤯", description: "Feeling mentally drained from making too many small decisions.", category: "Mental Wellness" },
  { name: "Ethical consumerism", emoji: "🌍", description: "The difficulty of finding products that are sustainable and ethically made.", category: "Shopping & Consumerism" },
  { name: "Finding clothes that fit", emoji: "👕", description: "The frustration of inconsistent sizing in clothing.", category: "Shopping & Consumerism" },
  { name: "Returning online purchases", emoji: "📦", description: "The hassle of packaging and sending back items bought online.", category: "Shopping & Consumerism" },
  { name: "Analysis paralysis", emoji: "🤔", description: "Overthinking a decision so much that a choice is never made.", category: "Productivity & Time Management" }
];
